**Task 1: Data Loading**

- Load the Titanic dataset from the following URL into a Pandas DataFrame: Titanic Dataset
- Display the first 5 rows of the DataFrame.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

In [ ]:
titanic_df = pd.read_csv(url)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Task 2: Summary Stats**

- Calculate and display the following statistics:
- Summary statistics for DataFrame
- Summary statistics (mean, std, min, max) for the 'Age' column.

**Task 3: Data Visualization**

- Create a histogram of the 'Age' column.
- Create a bar chart showing the number of passengers from each 'Embarked' location.
- Create a bar chart showing the survival rate for male and female passengers.

**Task 4: Data Manipulation**

- Replace missing values in the 'Age' column with the mean age of passengers.
- Create a new column 'FamilySize' that represents the sum of 'SibSp' and 'Parch' for each passenger.
- Group the data by 'Pclass' and calculate the mean fare for each class.

**Task 5: Data Visualization (Advanced)**

- Create a box plot to visualize the distribution of 'Fare' by 'Pclass'.
- Create a pair plot (scatterplot matrix) to visualize relationships between 'Age', 'Fare', and 'Survived'.

**Task 6 : Remove Outliers**
-  Remove outliers from 'Fare' by 3 STD

**Task 7: Data Visualization**

- Create a bar chart showing the survival count for each 'Pclass' (class of travel).

**Task 8: Data Visualization**

- Create a stacked bar chart showing the survival count for each 'Pclass' and 'Sex' combination.

**Task 9: Data Visualization (Advanced)**

Create a histogram of the 'Fare' column, with different colors for passengers who survived and those who did not.

**Task 10: Data Visualization (Advanced)**

- Create a scatter plot of 'Age' vs. 'Fare', with color-coded points for survivors and non-survivors.

**Task 11: Data Visualization (Advanced)**

- Create a box plot of 'Age' for each 'Pclass' to visualize the distribution of ages within each class.

In [ ]:
# happy learning :)